language: python
python:
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  install:
  # update pip to ensure extras_require format is supported
  - 'pip install --upgrade pip'
  - 'pip install ".[test]"

script: pytest # run tests
after_success:
  - codecov # submit coverage
